---
abstract: 'sub { shift; @_ }'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PerlX::ArraySkip
name: PerlX-ArraySkip
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=PerlX-ArraySkip
  homepage: https://metacpan.org/release/PerlX-ArraySkip
  license: http://creativecommons.org/publicdomain/zero/1.0/
  repository: https://github.com/tobyink/p5-perlx-arrayskip
version: 0.002
